import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { requireAdmin } from '@/lib/admin/auth';
import { createAdminClient } from '@/lib/supabase/admin';
import { recordAdminAudit } from '@/lib/cms/audit';

export const dynamic = 'force-dynamic';

function updateDiskOverride(productId: string, data: Record<string, any>) {
  try {
    const overridesPath = path.join(process.cwd(), 'catalog_overrides.json');
    let overrides: Record<string, any> = {};
    if (fs.existsSync(overridesPath)) {
      overrides = JSON.parse(fs.readFileSync(overridesPath, 'utf8'));
    }
    overrides[productId] = {
      ...(overrides[productId] || {}),
      ...data,
      updated_at: new Date().toISOString(),
    };
    fs.writeFileSync(overridesPath, JSON.stringify(overrides, null, 2), 'utf8');
  } catch (err) {
    console.error('Failed to update disk catalog override:', err);
  }
}

export async function POST(req: Request) {
  const auth = await requireAdmin(req);
  if (!auth.authorized || !auth.user) {
    return auth.errorResponse || NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body = await req.json();
    const { product_id } = body;

    if (!product_id) {
      return NextResponse.json({ success: false, error: 'product_id is required' }, { status: 400 });
    }

    // 1. Fetch original product
    let originalProduct: any = null;
    const supabase = createAdminClient();
    const { data, error } = await supabase.from('products').select('*').eq('id', product_id).single();
    if (!error && data) {
      originalProduct = data;
    } else {
      // Look in disk overrides
      const overridesPath = path.join(process.cwd(), 'catalog_overrides.json');
      if (fs.existsSync(overridesPath)) {
        const overrides = JSON.parse(fs.readFileSync(overridesPath, 'utf8'));
        if (overrides[product_id]) {
          originalProduct = { id: product_id, ...overrides[product_id] };
        }
      }
    }

    if (!originalProduct) {
      return NextResponse.json({ success: false, error: `Product ${product_id} not found` }, { status: 404 });
    }

    // 2. Build cloned product
    const timestamp = Date.now().toString().slice(-4);
    const newId = `${originalProduct.id}-copy-${timestamp}`;
    const newTitle = `${originalProduct.title} (Copy)`;
    const newSlug = originalProduct.slug ? `${originalProduct.slug}-copy-${timestamp}` : newId;
    const newSku = `NAM-${newId.toUpperCase().slice(0, 10)}`;

    const duplicatedProduct = {
      ...originalProduct,
      id: newId,
      slug: newSlug,
      sku: newSku,
      title: newTitle,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    // Remove any autogenerated primary key fields if DB generates them
    delete (duplicatedProduct as any)._id;

    // 3. Save to DB
    let dbPersisted = false;
    try {
      const { error: insertErr } = await supabase.from('products').insert([duplicatedProduct]);
      if (!insertErr) {
        dbPersisted = true;
      } else {
        console.warn('Supabase product duplicate insert warning:', insertErr.message);
      }
    } catch (err: any) {
      console.warn('Supabase duplicate error:', err?.message);
    }

    // 4. Update disk overrides
    updateDiskOverride(newId, duplicatedProduct);

    // 5. Log audit
    await recordAdminAudit(auth.user.email, 'DUPLICATE_PRODUCT', 'product', newId, {
      source_product_id: product_id,
      new_title: newTitle,
    });

    return NextResponse.json({
      success: true,
      message: 'Product duplicated successfully',
      product: duplicatedProduct,
      db_persisted: dbPersisted,
    });
  } catch (error: any) {
    console.error('Error duplicating product:', error);
    return NextResponse.json({ success: false, error: error?.message || 'Server error' }, { status: 500 });
  }
}
