/**
 * NAMORA — Strongly Typed Asset Manifest (Phase 3 Verified)
 * Auto-generated from canonical verified media repository.
 * Contains dimensions, aspect ratios, /assets/ paths, and legacy filename mappings.
 */

export interface AssetEntry {
  id: string;
  name: string;
  category: 'designs' | 'products/cars' | 'products/sports' | 'products/pop-culture' | 'products/names' | 'frames' | 'gallery' | 'hero' | 'icons' | 'branding' | 'video';
  path: string;
  width: number;
  height: number;
  aspectRatio: string;
  alt: string;
  originalFilename: string;
  legacyMapping: string;
  isA4Standard: boolean;
}

export const ASSET_MANIFEST: Record<string, AssetEntry> = {
  "design-1": {
    "id": "design-1",
    "name": "Red Persian Carpet Frame",
    "category": "designs",
    "path": "/assets/designs/design1.jpg",
    "width": 675,
    "height": 1200,
    "aspectRatio": "675:1200 (~0.5625)",
    "alt": "NAMORA Persian Calligraphy Frame — Red Persian Carpet Frame",
    "originalFilename": "design1.jpg",
    "legacyMapping": "design1.jpg",
    "isA4Standard": true
  },
  "design-2": {
    "id": "design-2",
    "name": "Emerald Traditional Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design2.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Emerald Traditional Persian Frame",
    "originalFilename": "design2.jpg",
    "legacyMapping": "design2.jpg",
    "isA4Standard": true
  },
  "design-3": {
    "id": "design-3",
    "name": "Royal Blue Medallion Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design3.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Royal Blue Medallion Persian Frame",
    "originalFilename": "design3.jpg",
    "legacyMapping": "design3.jpg",
    "isA4Standard": true
  },
  "design-4": {
    "id": "design-4",
    "name": "Antique Gold Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design4.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Antique Gold Persian Frame",
    "originalFilename": "design4.jpg",
    "legacyMapping": "design4.jpg",
    "isA4Standard": true
  },
  "design-5": {
    "id": "design-5",
    "name": "Midnight Black & Gold Frame",
    "category": "designs",
    "path": "/assets/designs/design5.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Midnight Black & Gold Frame",
    "originalFilename": "design5.jpg",
    "legacyMapping": "design5.jpg",
    "isA4Standard": true
  },
  "design-6": {
    "id": "design-6",
    "name": "Crimson Floral Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design6.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Crimson Floral Persian Frame",
    "originalFilename": "design6.jpg",
    "legacyMapping": "design6.jpg",
    "isA4Standard": true
  },
  "design-7": {
    "id": "design-7",
    "name": "Sapphire Crest Oriental Frame",
    "category": "designs",
    "path": "/assets/designs/design7.jpg",
    "width": 702,
    "height": 1200,
    "aspectRatio": "702:1200 (~0.5850)",
    "alt": "NAMORA Persian Calligraphy Frame — Sapphire Crest Oriental Frame",
    "originalFilename": "design7.jpg",
    "legacyMapping": "design7.jpg",
    "isA4Standard": true
  },
  "design-8": {
    "id": "design-8",
    "name": "Burgundy Medallion Frame",
    "category": "designs",
    "path": "/assets/designs/design8.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Burgundy Medallion Frame",
    "originalFilename": "design8.jpg",
    "legacyMapping": "design8.jpg",
    "isA4Standard": true
  },
  "design-9": {
    "id": "design-9",
    "name": "Turquoise Silk Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design9.jpg",
    "width": 720,
    "height": 1280,
    "aspectRatio": "720:1280 (~0.5625)",
    "alt": "NAMORA Persian Calligraphy Frame — Turquoise Silk Persian Frame",
    "originalFilename": "design9.jpg",
    "legacyMapping": "design9.jpg",
    "isA4Standard": true
  },
  "design-10": {
    "id": "design-10",
    "name": "Maroon Heritage Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design10.jpg",
    "width": 675,
    "height": 1200,
    "aspectRatio": "675:1200 (~0.5625)",
    "alt": "NAMORA Persian Calligraphy Frame — Maroon Heritage Persian Frame",
    "originalFilename": "design10.jpg",
    "legacyMapping": "design10.jpg",
    "isA4Standard": true
  },
  "design-11": {
    "id": "design-11",
    "name": "Teal Arch Oriental Frame",
    "category": "designs",
    "path": "/assets/designs/design11.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Teal Arch Oriental Frame",
    "originalFilename": "design11.jpg",
    "legacyMapping": "design11.jpg",
    "isA4Standard": true
  },
  "design-12": {
    "id": "design-12",
    "name": "Ruby Palace Carpet Frame",
    "category": "designs",
    "path": "/assets/designs/design12.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Ruby Palace Carpet Frame",
    "originalFilename": "design12.jpg",
    "legacyMapping": "design12.jpg",
    "isA4Standard": true
  },
  "design-13": {
    "id": "design-13",
    "name": "Cobalt Mosaic Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design13.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Cobalt Mosaic Persian Frame",
    "originalFilename": "design13.jpg",
    "legacyMapping": "design13.jpg",
    "isA4Standard": true
  },
  "design-14": {
    "id": "design-14",
    "name": "Amber Damask Oriental Frame",
    "category": "designs",
    "path": "/assets/designs/design14.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Amber Damask Oriental Frame",
    "originalFilename": "design14.jpg",
    "legacyMapping": "design14.jpg",
    "isA4Standard": true
  },
  "design-15": {
    "id": "design-15",
    "name": "Ivory Bloom Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design15.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Ivory Bloom Persian Frame",
    "originalFilename": "design15.jpg",
    "legacyMapping": "design15.jpg",
    "isA4Standard": true
  },
  "design-16": {
    "id": "design-16",
    "name": "Garnet Court Carpet Frame",
    "category": "designs",
    "path": "/assets/designs/design16.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Garnet Court Carpet Frame",
    "originalFilename": "design16.jpg",
    "legacyMapping": "design16.jpg",
    "isA4Standard": true
  },
  "design-17": {
    "id": "design-17",
    "name": "Lapis Garden Oriental Frame",
    "category": "designs",
    "path": "/assets/designs/design17.jpg",
    "width": 675,
    "height": 1200,
    "aspectRatio": "675:1200 (~0.5625)",
    "alt": "NAMORA Persian Calligraphy Frame — Lapis Garden Oriental Frame",
    "originalFilename": "design17.jpg",
    "legacyMapping": "design17.jpg",
    "isA4Standard": true
  },
  "design-18": {
    "id": "design-18",
    "name": "Bronze Scroll Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design18.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Bronze Scroll Persian Frame",
    "originalFilename": "design18.jpg",
    "legacyMapping": "design18.jpg",
    "isA4Standard": true
  },
  "design-19": {
    "id": "design-19",
    "name": "Scarlet Crown Oriental Frame",
    "category": "designs",
    "path": "/assets/designs/design19.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Scarlet Crown Oriental Frame",
    "originalFilename": "design19.jpg",
    "legacyMapping": "design19.jpg",
    "isA4Standard": true
  },
  "design-20": {
    "id": "design-20",
    "name": "Azure Oasis Carpet Frame",
    "category": "designs",
    "path": "/assets/designs/design20.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Azure Oasis Carpet Frame",
    "originalFilename": "design20.jpg",
    "legacyMapping": "design20.jpg",
    "isA4Standard": true
  },
  "design-21": {
    "id": "design-21",
    "name": "Onyx Lattice Persian Frame",
    "category": "designs",
    "path": "/assets/designs/design21.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Persian Calligraphy Frame — Onyx Lattice Persian Frame",
    "originalFilename": "design21.jpg",
    "legacyMapping": "design21.jpg",
    "isA4Standard": true
  },
  "car-1": {
    "id": "car-1",
    "name": "Porsche 911 GT3 RS",
    "category": "products/cars",
    "path": "/assets/products/cars/car1.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Automotive Wall Frame — Porsche 911 GT3 RS",
    "originalFilename": "car1.jpg",
    "legacyMapping": "car1.jpg",
    "isA4Standard": true
  },
  "car-2": {
    "id": "car-2",
    "name": "BMW M5 F90 Black Edition",
    "category": "products/cars",
    "path": "/assets/products/cars/car2.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Automotive Wall Frame — BMW M5 F90 Black Edition",
    "originalFilename": "car2.jpg",
    "legacyMapping": "car2.jpg",
    "isA4Standard": true
  },
  "car-3": {
    "id": "car-3",
    "name": "Porsche 911 GT3 Silver",
    "category": "products/cars",
    "path": "/assets/products/cars/car3.jpg",
    "width": 675,
    "height": 1200,
    "aspectRatio": "675:1200 (~0.5625)",
    "alt": "NAMORA Automotive Wall Frame — Porsche 911 GT3 Silver",
    "originalFilename": "car3.jpg",
    "legacyMapping": "car3.jpg",
    "isA4Standard": true
  },
  "car-4": {
    "id": "car-4",
    "name": "BMW M8 Competition Coupé",
    "category": "products/cars",
    "path": "/assets/products/cars/car4.jpg",
    "width": 736,
    "height": 980,
    "aspectRatio": "736:980 (~0.7510)",
    "alt": "NAMORA Automotive Wall Frame — BMW M8 Competition Coupé",
    "originalFilename": "car4.jpg",
    "legacyMapping": "car4.jpg",
    "isA4Standard": true
  },
  "car-5": {
    "id": "car-5",
    "name": "Porsche 911 GT3 Rear Wing",
    "category": "products/cars",
    "path": "/assets/products/cars/car5.jpg",
    "width": 736,
    "height": 921,
    "aspectRatio": "736:921 (~0.7991)",
    "alt": "NAMORA Automotive Wall Frame — Porsche 911 GT3 Rear Wing",
    "originalFilename": "car5.jpg",
    "legacyMapping": "car5.jpg",
    "isA4Standard": true
  },
  "car-6": {
    "id": "car-6",
    "name": "Porsche GT3 RS White Frame",
    "category": "products/cars",
    "path": "/assets/products/cars/car6.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Automotive Wall Frame — Porsche GT3 RS White Frame",
    "originalFilename": "car6.jpg",
    "legacyMapping": "car6.jpg",
    "isA4Standard": true
  },
  "car-7": {
    "id": "car-7",
    "name": "Porsche 911 GT3 RS Carbon Gray",
    "category": "products/cars",
    "path": "/assets/products/cars/car7.jpg",
    "width": 720,
    "height": 942,
    "aspectRatio": "720:942 (~0.7643)",
    "alt": "NAMORA Automotive Wall Frame — Porsche 911 GT3 RS Carbon Gray",
    "originalFilename": "car7.jpg",
    "legacyMapping": "car7.jpg",
    "isA4Standard": true
  },
  "car-8": {
    "id": "car-8",
    "name": "Porsche 911 GT3 RS 3D Diecast",
    "category": "products/cars",
    "path": "/assets/products/cars/car8.jpg",
    "width": 736,
    "height": 920,
    "aspectRatio": "736:920 (~0.8000)",
    "alt": "NAMORA Automotive Wall Frame — Porsche 911 GT3 RS 3D Diecast",
    "originalFilename": "car8.jpg",
    "legacyMapping": "car8.jpg",
    "isA4Standard": true
  },
  "car-9": {
    "id": "car-9",
    "name": "Ford Mustang 1964 Legendary",
    "category": "products/cars",
    "path": "/assets/products/cars/car9.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Automotive Wall Frame — Ford Mustang 1964 Legendary",
    "originalFilename": "car9.jpg",
    "legacyMapping": "car9.jpg",
    "isA4Standard": true
  },
  "car-10": {
    "id": "car-10",
    "name": "Supercar Showcase Edition",
    "category": "products/cars",
    "path": "/assets/products/cars/car10.mp4",
    "width": 1080,
    "height": 1920,
    "aspectRatio": "1080:1920 (~0.5625)",
    "alt": "NAMORA Automotive Wall Frame — Supercar Showcase Edition",
    "originalFilename": "car10.mp4",
    "legacyMapping": "car10.mp4",
    "isA4Standard": true
  },
  "car-11": {
    "id": "car-11",
    "name": "Porsche 911 RSR Triptych Wall Set",
    "category": "products/cars",
    "path": "/assets/products/cars/car11.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Automotive Wall Frame — Porsche 911 RSR Triptych Wall Set",
    "originalFilename": "car11.jpg",
    "legacyMapping": "car11.jpg",
    "isA4Standard": true
  },
  "sport-1": {
    "id": "sport-1",
    "name": "FC Barcelona Vintage Crest",
    "category": "products/sports",
    "path": "/assets/products/sports/sport1.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — FC Barcelona Vintage Crest",
    "originalFilename": "sport1.jpg",
    "legacyMapping": "sport1.jpg",
    "isA4Standard": true
  },
  "sport-2": {
    "id": "sport-2",
    "name": "Real Madrid - Hala Madrid",
    "category": "products/sports",
    "path": "/assets/products/sports/sport2.jpg",
    "width": 720,
    "height": 716,
    "aspectRatio": "720:716 (~1.0056)",
    "alt": "NAMORA Frame Edition — Real Madrid - Hala Madrid",
    "originalFilename": "sport2.jpg",
    "legacyMapping": "sport2.jpg",
    "isA4Standard": true
  },
  "sport-3": {
    "id": "sport-3",
    "name": "Lionel Messi - World Cup Triumph",
    "category": "products/sports",
    "path": "/assets/products/sports/sport3.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Frame Edition — Lionel Messi - World Cup Triumph",
    "originalFilename": "sport3.jpg",
    "legacyMapping": "sport3.jpg",
    "isA4Standard": true
  },
  "sport-4": {
    "id": "sport-4",
    "name": "Messi #10 Argentina Jersey Frame",
    "category": "products/sports",
    "path": "/assets/products/sports/sport4.jpg",
    "width": 718,
    "height": 889,
    "aspectRatio": "718:889 (~0.8076)",
    "alt": "NAMORA Frame Edition — Messi #10 Argentina Jersey Frame",
    "originalFilename": "sport4.jpg",
    "legacyMapping": "sport4.jpg",
    "isA4Standard": true
  },
  "sport-5": {
    "id": "sport-5",
    "name": "Lionel Messi #10 Accolades",
    "category": "products/sports",
    "path": "/assets/products/sports/sport5.jpg",
    "width": 736,
    "height": 920,
    "aspectRatio": "736:920 (~0.8000)",
    "alt": "NAMORA Frame Edition — Lionel Messi #10 Accolades",
    "originalFilename": "sport5.jpg",
    "legacyMapping": "sport5.jpg",
    "isA4Standard": true
  },
  "sport-6": {
    "id": "sport-6",
    "name": "FC Barcelona Leather Grain",
    "category": "products/sports",
    "path": "/assets/products/sports/sport6.jpg",
    "width": 580,
    "height": 580,
    "aspectRatio": "580:580 (~1.0000)",
    "alt": "NAMORA Frame Edition — FC Barcelona Leather Grain",
    "originalFilename": "sport6.jpg",
    "legacyMapping": "sport6.jpg",
    "isA4Standard": true
  },
  "sport-8": {
    "id": "sport-8",
    "name": "Jamal Musiala #10 Germany DFB",
    "category": "products/sports",
    "path": "/assets/products/sports/sport8.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Jamal Musiala #10 Germany DFB",
    "originalFilename": "sport8.jpg",
    "legacyMapping": "sport8.jpg",
    "isA4Standard": true
  },
  "sport-9": {
    "id": "sport-9",
    "name": "Neymar Jr #10 Brazil 3D Frame",
    "category": "products/sports",
    "path": "/assets/products/sports/sport9.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Neymar Jr #10 Brazil 3D Frame",
    "originalFilename": "sport9.jpg",
    "legacyMapping": "sport9.jpg",
    "isA4Standard": true
  },
  "sport-10": {
    "id": "sport-10",
    "name": "Messi #10 3D Layered Jersey",
    "category": "products/sports",
    "path": "/assets/products/sports/sport10.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Messi #10 3D Layered Jersey",
    "originalFilename": "sport10.jpg",
    "legacyMapping": "sport10.jpg",
    "isA4Standard": true
  },
  "sport-11": {
    "id": "sport-11",
    "name": "Força Barça - Més Que Un Club",
    "category": "products/sports",
    "path": "/assets/products/sports/sport11.jpg",
    "width": 645,
    "height": 795,
    "aspectRatio": "645:795 (~0.8113)",
    "alt": "NAMORA Frame Edition — Força Barça - Més Que Un Club",
    "originalFilename": "sport11.jpg",
    "legacyMapping": "sport11.jpg",
    "isA4Standard": true
  },
  "sport-12": {
    "id": "sport-12",
    "name": "Neymar Jr 1992 Brazil Signature",
    "category": "products/sports",
    "path": "/assets/products/sports/sport12.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Frame Edition — Neymar Jr 1992 Brazil Signature",
    "originalFilename": "sport12.jpg",
    "legacyMapping": "sport12.jpg",
    "isA4Standard": true
  },
  "sport-13": {
    "id": "sport-13",
    "name": "Jude Bellingham - England & Madrid",
    "category": "products/sports",
    "path": "/assets/products/sports/sport13.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Jude Bellingham - England & Madrid",
    "originalFilename": "sport13.jpg",
    "legacyMapping": "sport13.jpg",
    "isA4Standard": true
  },
  "sport-14": {
    "id": "sport-14",
    "name": "Cristiano Ronaldo - CR7 1985",
    "category": "products/sports",
    "path": "/assets/products/sports/sport14.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Cristiano Ronaldo - CR7 1985",
    "originalFilename": "sport14.jpg",
    "legacyMapping": "sport14.jpg",
    "isA4Standard": true
  },
  "sport-15": {
    "id": "sport-15",
    "name": "Neymar Jr - Santos FC Heritage",
    "category": "products/sports",
    "path": "/assets/products/sports/sport15.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Neymar Jr - Santos FC Heritage",
    "originalFilename": "sport15.jpg",
    "legacyMapping": "sport15.jpg",
    "isA4Standard": true
  },
  "sport-16": {
    "id": "sport-16",
    "name": "Spider-Man: Into the Spider-Verse",
    "category": "products/pop-culture",
    "path": "/assets/products/pop-culture/sport16.jpg",
    "width": 736,
    "height": 984,
    "aspectRatio": "736:984 (~0.7480)",
    "alt": "NAMORA Frame Edition — Spider-Man: Into the Spider-Verse",
    "originalFilename": "sport16.jpg",
    "legacyMapping": "sport16.jpg",
    "isA4Standard": true
  },
  "sport-18": {
    "id": "sport-18",
    "name": "Lewis Hamilton #44 Mercedes F1",
    "category": "products/pop-culture",
    "path": "/assets/products/pop-culture/sport18.jpg",
    "width": 736,
    "height": 736,
    "aspectRatio": "736:736 (~1.0000)",
    "alt": "NAMORA Frame Edition — Lewis Hamilton #44 Mercedes F1",
    "originalFilename": "sport18.jpg",
    "legacyMapping": "sport18.jpg",
    "isA4Standard": true
  },
  "name-1": {
    "id": "name-1",
    "name": "Tayyiba (طيبة) - Persian Blue",
    "category": "products/names",
    "path": "/assets/products/names/name1.jpg",
    "width": 736,
    "height": 929,
    "aspectRatio": "736:929 (~0.7922)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Tayyiba (طيبة) - Persian Blue",
    "originalFilename": "name1.jpg",
    "legacyMapping": "name1.jpg",
    "isA4Standard": true
  },
  "name-2": {
    "id": "name-2",
    "name": "Rimsha (رمشة) - Floral \"R\"",
    "category": "products/names",
    "path": "/assets/products/names/name2.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Rimsha (رمشة) - Floral \"R\"",
    "originalFilename": "name2.jpg",
    "legacyMapping": "name2.jpg",
    "isA4Standard": true
  },
  "name-3": {
    "id": "name-3",
    "name": "Muhammad (محمد) - Kilim Rug",
    "category": "products/names",
    "path": "/assets/products/names/name3.jpg",
    "width": 736,
    "height": 920,
    "aspectRatio": "736:920 (~0.8000)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Muhammad (محمد) - Kilim Rug",
    "originalFilename": "name3.jpg",
    "legacyMapping": "name3.jpg",
    "isA4Standard": true
  },
  "name-4": {
    "id": "name-4",
    "name": "Fatima (فاطمة) - Carpet Mosaic",
    "category": "products/names",
    "path": "/assets/products/names/name4.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Fatima (فاطمة) - Carpet Mosaic",
    "originalFilename": "name4.jpg",
    "legacyMapping": "name4.jpg",
    "isA4Standard": true
  },
  "name-5": {
    "id": "name-5",
    "name": "Batool (بتول) - Crimson Tapestry",
    "category": "products/names",
    "path": "/assets/products/names/name5.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Batool (بتول) - Crimson Tapestry",
    "originalFilename": "name5.jpg",
    "legacyMapping": "name5.jpg",
    "isA4Standard": true
  },
  "name-6": {
    "id": "name-6",
    "name": "Maryam (مريم) - Jasmine Flower",
    "category": "products/names",
    "path": "/assets/products/names/name6.jpg",
    "width": 736,
    "height": 1308,
    "aspectRatio": "736:1308 (~0.5627)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Maryam (مريم) - Jasmine Flower",
    "originalFilename": "name6.jpg",
    "legacyMapping": "name6.jpg",
    "isA4Standard": true
  },
  "name-7": {
    "id": "name-7",
    "name": "Fatima (فاطمة) - Heritage Rug",
    "category": "products/names",
    "path": "/assets/products/names/name7.jpg",
    "width": 736,
    "height": 920,
    "aspectRatio": "736:920 (~0.8000)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Fatima (فاطمة) - Heritage Rug",
    "originalFilename": "name7.jpg",
    "legacyMapping": "name7.jpg",
    "isA4Standard": true
  },
  "name-8": {
    "id": "name-8",
    "name": "Ahmad (أحمد) - Handheld Photo",
    "category": "products/names",
    "path": "/assets/products/names/name8.jpg",
    "width": 736,
    "height": 920,
    "aspectRatio": "736:920 (~0.8000)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Ahmad (أحمد) - Handheld Photo",
    "originalFilename": "name8.jpg",
    "legacyMapping": "name8.jpg",
    "isA4Standard": true
  },
  "name-9": {
    "id": "name-9",
    "name": "Fatima (فاطمة) - Blush Floral",
    "category": "products/names",
    "path": "/assets/products/names/name9.png",
    "width": 1086,
    "height": 134348800,
    "aspectRatio": "1086:134348800 (~0.0000)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Fatima (فاطمة) - Blush Floral",
    "originalFilename": "name9.png",
    "legacyMapping": "name9.png",
    "isA4Standard": true
  },
  "name-10": {
    "id": "name-10",
    "name": "Fatima (فاطمة) - Royal Purple",
    "category": "products/names",
    "path": "/assets/products/names/name10.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Fatima (فاطمة) - Royal Purple",
    "originalFilename": "name10.jpg",
    "legacyMapping": "name10.jpg",
    "isA4Standard": true
  },
  "name-11": {
    "id": "name-11",
    "name": "Sabr (صبر - Patience)",
    "category": "products/names",
    "path": "/assets/products/names/name11.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Artistic Name Calligraphy Frame — Sabr (صبر - Patience)",
    "originalFilename": "name11.jpg",
    "legacyMapping": "name11.jpg",
    "isA4Standard": true
  },
  "frame-lookbook-1": {
    "id": "frame-lookbook-1",
    "name": "Fatima Red Persian Frame Lookbook Sample",
    "category": "frames",
    "path": "/assets/frames/frame1.jpg",
    "width": 736,
    "height": 981,
    "aspectRatio": "736:981 (~0.7503)",
    "alt": "NAMORA Handmade Personalized Wall Frame Review Photo",
    "originalFilename": "frame1.jpg",
    "legacyMapping": "frame1.jpg",
    "isA4Standard": true
  },
  "hero-video-bg": {
    "id": "hero-video-bg",
    "name": "NAMORA Hero Background Showcase Video",
    "category": "hero",
    "path": "/assets/hero/hero-video.mp4",
    "width": 1080,
    "height": 1920,
    "aspectRatio": "9:16 (Vertical Cinematic)",
    "alt": "NAMORA Luxury Handcrafted Wall Frames Showcase Video",
    "originalFilename": "hero-video.mp4",
    "legacyMapping": "hero-video.mp4",
    "isA4Standard": false
  }
};

export const PERSIAN_DESIGNS_MANIFEST = Object.values(ASSET_MANIFEST).filter(
  (a) => a.category === 'designs'
);

export const READY_STOCK_MANIFEST = Object.values(ASSET_MANIFEST).filter(
  (a) => a.category.startsWith('products/')
);

export function getAssetByLegacyFilename(filename: string): AssetEntry | undefined {
  return Object.values(ASSET_MANIFEST).find(
    (a) => a.legacyMapping === filename || a.originalFilename === filename
  );
}

export function getAssetById(id: string): AssetEntry | undefined {
  return ASSET_MANIFEST[id];
}
